// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC38mapy5t-s7g0IIl3zFATzH7rF7Gms9w',
    appId: '1:793097928357:android:9b5dfb9beb58b4ecb2d74c',
    messagingSenderId: '793097928357',
    projectId: 'se100p13-nerdhub',
    storageBucket: 'se100p13-nerdhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZjfTpb091EdXcq1mlD6MGPDKSujHBn0',
    appId: '1:793097928357:ios:b731a7442d16da7fb2d74c',
    messagingSenderId: '793097928357',
    projectId: 'se100p13-nerdhub',
    storageBucket: 'se100p13-nerdhub.firebasestorage.app',
    iosClientId: '793097928357-plto1r3549n60b0d46q6tpipitrl8gmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodgadget',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTyMnvllITeRrLX1UQRynaZ5_D-icwxQg',
    appId: '1:793097928357:web:9f39111219883d2eb2d74c',
    messagingSenderId: '793097928357',
    projectId: 'se100p13-nerdhub',
    authDomain: 'se100p13-nerdhub.firebaseapp.com',
    storageBucket: 'se100p13-nerdhub.firebasestorage.app',
    measurementId: 'G-3VC79RFBJB',
  );

}